### PR TITLE
Add support for Laravel 11

### PR DESCRIPTION
**Pull request by janyksteenbeek**
This PR changes the composer.json to allow Laravel 11 deps.

### CODE REVIEW

**Comment by pieterhielkema** [comment]
Really need this +1 ❤️

**Comment by JamesHemery** [comment]
@janyksteenbeek thanks, can you add Laravel 11 to matrix in tests workflow ? You'll need to exclude PHP8.1 w/ L11

**Comment by janyksteenbeek** [comment]
should be good now! @JamesHemery

**Comment by JamesHemery** [comment]
@janyksteenbeek some tests fails, can you check ?

**Comment by joemugen** [comment]
A working PR has been merge #32 
[The release 0.0.14 is available](https://github.com/YieldStudio/laravel-expo-notifier/releases/tag/0.0.14)

**Pull request closed without merging**
